### ISSUE TITLE
Cell types of human heart ISS data

### ISSUE THREAD

**Issue by ttgump** [JiawenChenn/St-review#1]
Hi,
Where can I find the cell type proportions of human heart ISS data?

**Comment by JiawenChenn** [comment]
Hi,

All the cell type labels are in the mta.tsv files. For heart ISS data, it is in the internal folder.

**Comment by ttgump** [comment]
Hi,
I can find the internal mta file in the ISS internal folder, my question is how can I find the cell type of ISS spatial data? Thanks.
