### ISSUE TITLE
Result files of each algorithm in the main graph

### ISSUE THREAD

**Issue by lzygenomics** [JiawenChenn/St-review#2]
Dear @JiawenChenn 

Thank you for your fascinating work ! It is very friendly for users and developers. 
Could you please upload the result files of each algorithm in the main graph, so that the subsequent algorithm developers can insert their own algorithms for comparison ~?

Best wishes!

**Comment by JiawenChenn** [comment]
Hi @lzygenomics ,

Thanks for your comment. We will upload the result files soon. In the meantime, we recommend you to check whether the methods we evaluated have new version of source code/pipeline and make sure you are comparing to the up-to-date algorithms. The pipeline/software version we used could be found in the supplementary information. 

Best,
Jiawen

**Comment by lzygenomics** [comment]
> Hi @lzygenomics ,
> 
> Thanks for your comment. We will upload the result files soon. In the meantime, we recommend you to check whether the methods we evaluated have new version of source code/pipeline and make sure you are comparing to the up-to-date algorithms. The pipeline/software version we used could be found in the supplementary information.
> 
> Best, Jiawen

Thank you for your quick reply and detailed suggestions. It's really helpful ~
