### ISSUE TITLE
calc.mse function

### ISSUE THREAD

**Issue by Peiyao-Z** [JiawenChenn/St-review#4]
Hi, thank you for the great work! I'm trying to reproduce your result with the defined criteria but I didn't find the calc.mse funciton to calculate rmse or the library named 'funfun'. Do you have any suggestion on this?

Thank you!

**Comment by JiawenChenn** [comment]
Hi,

I think you can manually add this function using the source code here: https://rdrr.io/github/stas-g/funfun/src/R/calc_mse.R
Hope this helps.
